# Generated by Django 3.2.7 on 2022-03-07 00:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('categoryType', models.CharField(max_length=1)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('paymentTypeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payType', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('providerId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('phoneNumber', models.BigIntegerField()),
                ('offer', models.FloatField()),
                ('address', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('userTypeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('userType', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phoneNumber', models.BigIntegerField(null=True)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('userTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('tax', models.FloatField()),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stock', models.IntegerField()),
                ('entryDate', models.DateField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.product')),
                ('providerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('paymentTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.paymenttype')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.product')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.user')),
            ],
        ),
    ]
