# Generated by Django 3.2.7 on 2022-03-19 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('firstName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('phoneNumber', models.BigIntegerField(null=True)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('categoryType', models.CharField(choices=[('N', 'Nacional'), ('I', 'Importado'), ('V', 'Verduras_Hortalizas')], max_length=30)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('paymentTypeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payType', models.CharField(choices=[('E', 'Efectivo'), ('T', 'Tarjeta')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('providerId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('phoneNumber', models.BigIntegerField()),
                ('offer', models.FloatField()),
                ('address', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('tax', models.FloatField()),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('categoryId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductCategoryList', to='authApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stock', models.IntegerField()),
                ('entryDate', models.DateField()),
                ('productId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryProductList', to='authApp.product')),
                ('providerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryProviderList', to='authApp.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('billId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('paymentTypeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billPaymentTypeList', to='authApp.paymenttype')),
                ('productId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billProductList', to='authApp.product')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billUserList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
