# Generated by Django 3.2.7 on 2022-03-09 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='paymentTypeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billPaymentTypeList', to='authApp.paymenttype'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='productId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billProductList', to='authApp.product'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billUserList', to='authApp.user'),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryType',
            field=models.CharField(choices=[{'N', 'Nacional'}, {'Importado', 'I'}, {'Verduras_Hortalizas', 'V'}], max_length=30),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='productId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryProductList', to='authApp.product'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='providerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryProviderList', to='authApp.provider'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='payType',
            field=models.CharField(choices=[{'Efectivo', 'E'}, {'T', 'Tarjeta'}], max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductCategoryList', to='authApp.category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='userTypeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userTypeList', to='authApp.usertype'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='userType',
            field=models.CharField(choices=[{'Administrador', 'A'}, {'N', 'Natural'}], max_length=15),
        ),
    ]
