# Generated by Django 3.2.7 on 2022-03-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_auto_20220319_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank='True', null=True, upload_to='product/%Y/%m', verbose_name='Picture'),
        ),
    ]
