# Generated by Django 3.2.7 on 2022-03-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryType',
            field=models.CharField(choices=[('Nacional', 'Nacional'), ('Importado', 'Importado'), ('Verduras_Hortalizas', 'Verduras_Hortalizas')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank='True', null=True, upload_to=''),
        ),
    ]
