# Generated by Django 3.2.7 on 2022-03-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_auto_20220320_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank='True', default='productDefault.png', null=True, upload_to=''),
        ),
    ]
