# Generated by Django 3.2.7 on 2022-03-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_auto_20220302_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.BigIntegerField(null=True),
        ),
    ]
